### ISSUE TITLE
Bug on android 10 and 11

### ISSUE THREAD

**Issue by sanabousaid2021** [Gustash/react-native-image-keyboard#13]
Hello, I had a bug on android 10, when I add a gif from the keyboard, the gif is as if it has not been loaded, and I cannot add it to the formdata

https://user-images.githubusercontent.com/84022857/117819156-ca8c7180-b258-11eb-8a2b-3ad8e8764667.mp4

**Comment by Gustash** [comment]
From the video I can't tell what the problem is. Can you `console.log` the response from `onImageChange` and paste it here?

**Comment by sanabousaid2021** [comment]
the gif not showing up even if the link is correct cf attchements 
<img width="659" alt="Capture d’écran 2021-05-11 à 13 15 06" src="https://user-images.githubusercontent.com/84022857/117821520-353eac80-b25b-11eb-9f56-7c59786c12ec.png">
<img width="1558" alt="Capture d’écran 2021-05-11 à 13 15 48" src="https://user-images.githubusercontent.com/84022857/117821536-396aca00-b25b-11eb-922e-639df68607a9.png">

**Comment by Gustash** [comment]
Interesting. Can you share the project with me so I can debug this? I've never seen this behaviour before, might be something specific to your project/device, or an update that Google released that breaks the behaviour of this package.

**Comment by sanabousaid2021** [comment]
can you send me your bitbucket account

**Comment by Gustash** [comment]
Of course, my username on BB is `gustash`

**Comment by sanabousaid2021** [comment]
I need your email send it to me in this adresse ***@***.***

**Comment by sanabousaid2021** [comment]
i cant add you with your username would you please send me your email, i need your help thank you

**Comment by Gustash** [comment]
You should be able to give me access to the repo without my email.

https://stackoverflow.com/a/18824258

**Comment by sanabousaid2021** [comment]
i added you in bitbucket with email i found in this page https://github.com/Gustash

**Comment by Gustash** [comment]
@sanabousaid2021 so it seems like something has changed either on Android, or on Gboard. The `uri` used to be a file path, but now it's a content uri. This means you can't render it directly anymore.

You have a couple options here, which I'll order by the ones I recommend you try first:

1. Just use the `linkUri` instead of the `uri`. You'll need to check if this exists first though, as it's optional and some keyboards/GIFs might not provide this. The `linkUri` is the `http/https` link to the image on the internet.

2. Use the `data` value instead of the `uri`. This is a base64 representation of the image, but it's not my first recommendation since base64 is extremely bulky and slow for images, especially for animated ones.

3. Try something like [this](https://stackoverflow.com/questions/36259339/convert-content-uri-to-actual-path-for-android-using-react-native). The reason I'm recommending this last is because you'd need to install 2 extra libraries, and not all content uris lead to a file in the Android system, so this might still fail for other third-party keyboards.

Let me know if any of these solutions work for you.

**Comment by Gustash** [comment]
If you have your own server, you might be able to upload the content Uri as form data to your API. That would probably be a good fallback in case there is no linkUri

**Comment by sanabousaid2021** [comment]
ok i will  try this solution and i will tell you

**Comment by sanabousaid2021** [comment]
thank you so much you saved me, i used linkUri  just for android and let uri on ios ??

**Comment by Gustash** [comment]
> thank you so much you saved me, i used linkUri  just for android and let uri on ios ??

You can just check for the linkUri because that will always be undefined on iOS, so you can reuse the uri upload logic from iOS on Android, in case you don't get a linkUri there either
