### ISSUE TITLE
Should hide tooltip if there is nothing to be pasted

### ISSUE THREAD

**Issue by JungHsuan** [Gustash/react-native-image-keyboard#5]
Double clicking the ``TextInput`` will show the tooltip even if there is nothing to paste.
Pasting null to ``TextInput`` will cause crash on iOS.

Crash message:
NSInvalidArgumentException
-[RCTMultilineTextInputView paste:]: unrecognized selector sent to instance 0x151fbb510

Screenshot:
![93322285-b917d480-f845-11ea-9377-d82d0eea72a7](https://user-images.githubusercontent.com/10951814/93408613-90382380-f8c7-11ea-98eb-78d3a6967469.gif)

Xcode console:
![IMG_4244](https://user-images.githubusercontent.com/10951814/93408655-ae058880-f8c7-11ea-9b49-2115d00205e4.JPG)

**Comment by Gustash** [comment]
This should be fixed on v2.0.1, thanks to @mbouxin! Please try that version and open a new issue if the crash still persists.

Regarding hiding the tooltip when the pasteboard is empty, that seems to not be the intended behavior on iOS, since Safari.app also shows a tooltip for pasting, even when the pasteboard is empty.
